BEGIN;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

DROP TABLE IF EXISTS game_players;
DROP TABLE IF EXISTS game_state_history;
DROP TABLE IF EXISTS user_deck_cards;
DROP TABLE IF EXISTS user_decks;
DROP TABLE IF EXISTS cards;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS games;

-- ####### USERS
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4()
    , display_name VARCHAR(255) NOT NULL
    , username VARCHAR(255) NOT NULL
    , password VARCHAR(255) NOT NULL
    , created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
    , updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);
-- #######

-- ####### CARDS/DECKS 
CREATE TABLE cards (
    id SERIAL PRIMARY KEY
    , name VARCHAR(255) NOT NULL
    , description TEXT
    , type VARCHAR(255) NOT NULL
    , created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
    , updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE user_decks (
    id UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4()
    , user_id UUID NOT NULL
    , name VARCHAR(255) NOT NULL
    , description TEXT
    , created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
    , updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
    , FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE user_deck_cards (
    card_id SERIAL NOT NULL
    , user_deck_id UUID NOT NULL
    , quantity INT NOT NULL DEFAULT 1
    , PRIMARY KEY (card_id, user_deck_id)
	, FOREIGN KEY (card_id) REFERENCES cards(id) ON DELETE CASCADE
	, FOREIGN KEY (user_deck_id) REFERENCES user_decks(id) ON DELETE CASCADE
);
-- #######

-- ####### GAMES
CREATE TABLE games (
    id UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4()
    , turns INT NOT NULL DEFAULT 0
    , is_active BOOLEAN NOT NULL DEFAULT TRUE
    , created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
    , updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE game_players (
    game_id UUID NOT NULL
    , user_id UUID NOT NULL
    , result VARCHAR(255) NOT NULL
    , PRIMARY KEY (game_id, user_id)
    , FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE
    , FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE game_state_history (
    game_id UUID NOT NULL PRIMARY KEY
    , state JSONB NOT NULL
    , turn INT NOT NULL
    , created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
    , FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE
);
-- #######

COMMIT;